-- Task 1
SELECT * 
FROM DEPT d;
-- Task 2
SELECT * 
FROM EMP e;
-- Task 3
SELECT ENAME, DEPTNO, SAL 
FROM EMP e WHERE SAL >= 1600 AND SAL <= 3000;
-- Task 4
SELECT DEPTNO, DNAME 
FROM DEPT d ORDER BY DNAME ASC;
-- Task 5
SELECT DISTINCT(JOB) 
FROM EMP e ORDER BY JOB ASC;
-- Task 6
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO 
FROM EMP e WHERE DEPTNO = 10 OR DEPTNO = 30 ORDER BY ENAME ASC;
-- Task 7
SELECT ENAME, SAL * 12 AS ANNUAL, COMM FROM EMP e WHERE SAL > COMM ORDER BY SAL DESC;
-- Task 8
SELECT ENAME 
|| ' has held the position of ' 
|| JOB 
|| ' in department ' 
|| DEPTNO  
|| ' since '
|| HIREDATE 
FROM EMP e;
-- Task 9
SELECT ENAME, JOB FROM EMP WHERE JOB = 'CLERK' AND DEPTNO = 20;
-- Task 10
SELECT ENAME FROM EMP e WHERE ENAME LIKE '%TH%' OR ENAME LIKE '%LL%'
-- Task 11
SELECT ENAME, JOB, MGR, SAL FROM EMP e WHERE MGR IS NOT NULL;
-- Task 12
SELECT ENAME, SAL * 12 AS ANNUAL_SALARY FROM EMP e;
-- Task 13
SELECT ENAME, DEPTNO, HIREDATE FROM EMP e WHERE EXTRACT(YEAR FROM HIREDATE) = 1987;