package org.kloud.common;

/**
 * {@link org.kloud.model.user.User User} permissions basically
 */
public enum UserCapability {
    CHANGE_SELF_PASSWORD, CHANGE_CUSTOMER_PASSWORD, CHANGE_ADMIN_PASSWORD,
    WRITE_PRODUCTS, // TODO: Add 'created by' field to product for more granular permissions
    RW_SELF_WAREHOUSES, READ_OTHER_WAREHOUSES, WRITE_OTHER_WAREHOUSES,
    READ_CUSTOMERS, WRITE_CUSTOMERS, READ_MANAGERS, WRITE_MANAGERS, READ_ADMINS, WRITE_ADMINS,
    RW_SELF_COMMENTS, READ_OTHER_COMMENTS, WRITE_OTHER_COMMENTS,
    RW_SELF_ORDERS, READ_OTHER_ORDERS, WRITE_OTHER_ORDERS, RW_SELF_ASSIGNED_ORDERS, READ_OTHER_ASSIGNED_ORDERS, WRITE_OTHER_ASSIGNED_ORDERS
}
