package org.kloud.common;

/**
 * {@link org.kloud.model.user.User User} permissions basically
 */
public enum UserCapability {
    CHANGE_SELF_PASSWORD, CHANGE_CUSTOMER_PASSWORD, CHANGE_ADMIN_PASSWORD,
    RW_SELF_PRODUCTS, READ_OTHER_PRODUCTS, WRITE_OTHER_PRODUCTS,
    RW_SELF_WAREHOUSES, READ_OTHER_WAREHOUSES, WRITE_OTHER_WAREHOUSES,
    READ_MANAGERS, WRITE_MANAGERS, READ_ADMINS, WRITE_ADMINS
}
