/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GraphvizPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/setting.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  dotPath: "dot",
  pdflatexPath: "pdflatex",
  imageMagickConvertPath: "convert"
};
var GraphvizSettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(plugin) {
    super(plugin.app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Pdflatex Path").setDesc("Pdflatex executable path").addText(
      (text) => text.setPlaceholder(DEFAULT_SETTINGS.pdflatexPath).setValue(this.plugin.settings.pdflatexPath).onChange(
        (value) => __async(this, null, function* () {
          this.plugin.settings.pdflatexPath = value;
          yield this.plugin.saveSettings();
        })
      )
    );
    new import_obsidian.Setting(containerEl).setName("Dot Path").setDesc("Dot executable path").addText(
      (text) => text.setPlaceholder(DEFAULT_SETTINGS.dotPath).setValue(this.plugin.settings.dotPath).onChange(
        (value) => __async(this, null, function* () {
          this.plugin.settings.dotPath = value;
          yield this.plugin.saveSettings();
        })
      )
    );
  }
};

// src/processors.ts
var os = __toESM(require("os"));
var path = __toESM(require("path"));
var fs = __toESM(require("fs"));
var import_child_process = require("child_process");
var crypto = __toESM(require("crypto"));
var md5 = (contents) => crypto.createHash("md5").update(contents).digest("hex");
var Processors = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  getRenderer(type) {
    switch (type) {
      case "dot":
        return this.plugin.settings.dotPath;
      case "latex":
        return this.plugin.settings.pdflatexPath;
    }
  }
  spawnProcess(cmdPath, parameters) {
    return new Promise((resolve, reject) => {
      console.debug(`Starting external process ${cmdPath}, ${parameters}`);
      const process = (0, import_child_process.spawn)(cmdPath, parameters);
      let errData = "";
      process.stderr.on("data", (data) => {
        errData += data;
      });
      process.on("error", (err) => reject(`"${cmdPath} ${parameters}" failed, ${err}`));
      process.stdin.end();
      process.on("exit", (code) => {
        if (code !== 0) {
          return reject(`"${cmdPath} ${parameters}" failed, error code: ${code}, stderr: ${errData}`);
        }
        resolve("");
      });
    });
  }
  writeRenderedFile(sourceFile, type) {
    return __async(this, null, function* () {
      const cmdPath = this.getRenderer(type);
      const out = `${sourceFile}.png`;
      if (fs.existsSync(out)) {
        return out;
      }
      const parameters = type === "dot" ? ["-Tpng", sourceFile, "-o", out] : ["-shell-escape", "-output-directory", this.getTempDir(type), sourceFile];
      yield this.spawnProcess(cmdPath, parameters);
      if (type === "latex") {
        yield this.spawnProcess(this.plugin.settings.imageMagickConvertPath, ["-density", "300", "-units", "PixelsPerInch", `${sourceFile}.pdf[0]`, out]);
      }
      return out;
    });
  }
  getTempDir(type) {
    return path.join(os.tmpdir(), `obsidian-${type}`);
  }
  convertToImage(source, type) {
    return __async(this, null, function* () {
      const dir = this.getTempDir(type);
      const file = path.join(dir, md5(source));
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir);
      }
      if (!fs.existsSync(file)) {
        fs.writeFileSync(file, source);
      }
      return this.writeRenderedFile(file, type);
    });
  }
  dotProcessor(source, el, _) {
    return __async(this, null, function* () {
      return this.imageProcessor(source, el, _, "dot");
    });
  }
  latexProcessor(source, el, _) {
    return __async(this, null, function* () {
      return this.imageProcessor(source, el, _, "latex");
    });
  }
  imageProcessor(source, el, _, type) {
    return __async(this, null, function* () {
      try {
        console.debug(`Call image processor for ${type}`);
        if (type === "dot" && source.trimEnd().at(-1) != "}") {
          console.error("Bad source, won't render");
          return;
        }
        const imagePath = yield this.convertToImage(source, type);
        const img = document.createElement("img");
        img.src = `app://local${imagePath}`;
        el.appendChild(img);
      } catch (errMessage) {
        console.error("convert to image error: " + errMessage);
        const pre = document.createElement("pre");
        const code = document.createElement("code");
        pre.appendChild(code);
        code.setText(errMessage);
        el.appendChild(pre);
      }
    });
  }
};

// src/main.ts
var GraphvizPlugin = class extends import_obsidian2.Plugin {
  onload() {
    return __async(this, null, function* () {
      console.debug("Load graphviz - latex plugin");
      yield this.loadSettings();
      this.addSettingTab(new GraphvizSettingsTab(this));
      const processors = new Processors(this);
      this.app.workspace.onLayoutReady(() => {
        this.registerMarkdownCodeBlockProcessor("dot", processors.dotProcessor.bind(processors));
        this.registerMarkdownCodeBlockProcessor("latex", processors.latexProcessor.bind(processors));
      });
    });
  }
  onunload() {
    console.debug("Unload graphviz plugin");
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, yield this.loadData());
      return Promise.resolve();
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
};
