DROP TABLE SHOPS cascade constraints;
DROP TABLE WAREHOUSES cascade constraints;
DROP TABLE TUSERS cascade constraints;
DROP TABLE CARTS cascade constraints;
DROP TABLE PRODUCTS cascade constraints;
DROP TABLE COMMENTS cascade constraints;

CREATE TABLE SHOPS (
	id number(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	description varchar2(255 char) NULL,
	title varchar2(255 char) NULL,
	CONSTRAINT "Shop_pkey" PRIMARY KEY (id)
);


CREATE TABLE WAREHOUSES (
	id number(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	address varchar2(255 char) NULL,
	CONSTRAINT "Warehouse_pkey" PRIMARY KEY (id)
);



CREATE TABLE TUSERS (
	"birthDate" date NULL,
	id number(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"isAdmin" char(1) NULL,
	shop_id number(10) NULL,
	warehouse_id number(10) NULL,
	"DTYPE" varchar2(31 char) NOT NULL,
	"billingAddress" varchar2(255 char) NULL,
	"cardNumber" varchar2(255 char) NULL,
	login varchar2(255 char) NULL,
	"name" varchar2(255 char) NULL,
	"password" varchar2(255 char) NULL,
	"shippingAddress" varchar2(255 char) NULL,
	surname varchar2(255 char) NULL,
	CONSTRAINT "User_pkey" PRIMARY KEY (id),
	CONSTRAINT "FK_users_shop_id" FOREIGN KEY (shop_id) REFERENCES SHOPS(id),
	CONSTRAINT "FK_users_warehouse_id" FOREIGN KEY (warehouse_id) REFERENCES WAREHOUSES(id)
);



CREATE TABLE CARTS (
	product_id number(10) NULL,
	group_id number(10) NULL,
	customer_id number(10) NULL,
	id number(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	manager_id number(10) NULL,
	CONSTRAINT "Cart_pkey" PRIMARY KEY (id),
	CONSTRAINT "FK_cart_product_id" FOREIGN KEY (product_id) REFERENCES PRODUCTS(id),
	CONSTRAINT "FK_cart_manager_id" FOREIGN KEY (manager_id) REFERENCES TUSERS(id),
	CONSTRAINT "FK_cart_customer_id" FOREIGN KEY (customer_id) REFERENCES TUSERS(id)
);





CREATE TABLE PRODUCTS (
	id number(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	price binary_float NOT NULL,
	quantity number(10) NOT NULL,
	shop_id number(10) NULL,
	warehouse_id number(10) NULL,
	description varchar2(255 char) NULL,
	title varchar2(255 char) NULL,
	CONSTRAINT "Product_pkey" PRIMARY KEY (id),
	CONSTRAINT "FK_prod_warehouse_id" FOREIGN KEY (warehouse_id) REFERENCES WAREHOUSES(id),
	CONSTRAINT "FK_prod_shop_id" FOREIGN KEY (shop_id) REFERENCES SHOPS(id)
);





CREATE TABLE COMMENTS (
	"commentOwner_id" number(10) NULL,
	id number(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"parentComment_id" number(10) NULL,
	rating binary_float NOT NULL,
	"whichProductCommented_id" number(10) NULL,
	"commentBody" varchar2(255 char) NULL,
	"commentTitle" varchar2(255 char) NULL,
	CONSTRAINT "Comment_pkey" PRIMARY KEY (id),
	CONSTRAINT "FK_comment_whichProductCommented_id" FOREIGN KEY ("whichProductCommented_id") REFERENCES PRODUCTS(id),
	CONSTRAINT "FK_comment_parentComment_id" FOREIGN KEY ("parentComment_id") REFERENCES COMMENTS(id),
	CONSTRAINT "FK_comment_commentOwner_id" FOREIGN KEY ("commentOwner_id") REFERENCES TUSERS(id)
);





-- Sample Data for SHOPS Table (20 Rows)
-- Note: ID is auto-generated, so it's not included in the INSERT statements.
INSERT INTO SHOPS (description, title) VALUES ('Wide range of electronics and gadgets', 'Tech Universe');
INSERT INTO SHOPS (description, title) VALUES ('Latest fashion trends for all ages', 'Style Hub');
INSERT INTO SHOPS (description, title) VALUES ('All your grocery needs under one roof', 'FreshMart');
INSERT INTO SHOPS (description, title) VALUES ('Books, magazines, and stationery', 'The Reading Corner');
INSERT INTO SHOPS (description, title) VALUES ('Home furniture and decor', 'Cozy Homes');
INSERT INTO SHOPS (description, title) VALUES ('Sporting goods and outdoor equipment', 'Adventure Gear');
INSERT INTO SHOPS (description, title) VALUES ('Toys and games for kids', 'PlayWorld');
INSERT INTO SHOPS (description, title) VALUES ('Health and beauty products', 'Glamour Spot');
INSERT INTO SHOPS (description, title) VALUES ('DIY tools and hardware supplies', 'BuildIt Center');
INSERT INTO SHOPS (description, title) VALUES ('Pet food and accessories', 'Paws & Claws');
INSERT INTO SHOPS (description, title) VALUES ('Musical instruments and accessories', 'Melody Makers');
INSERT INTO SHOPS (description, title) VALUES ('Art supplies and craft materials', 'Creative Canvas');
INSERT INTO SHOPS (description, title) VALUES ('Car parts and accessories', 'AutoZone Plus');
INSERT INTO SHOPS (description, title) VALUES ('Gardening tools and plants', 'Green Thumbs');
INSERT INTO SHOPS (description, title) VALUES ('Office supplies and furniture', 'WorkSpace Solutions');
INSERT INTO SHOPS (description, title) VALUES ('Specialty coffee and tea blends', 'The Daily Grind');
INSERT INTO SHOPS (description, title) VALUES ('Bakery offering fresh bread and pastries', 'Sweet Treats Bakery');
INSERT INTO SHOPS (description, title) VALUES ('Organic and locally sourced produce', 'Nature''s Bounty');
INSERT INTO SHOPS (description, title) VALUES ('Kitchenware and small appliances', 'Culinary Essentials');
INSERT INTO SHOPS (description, title) VALUES ('Travel agency and booking services', 'Global Journeys');

-- Sample Data for WAREHOUSES Table (20 Rows)
-- Note: ID is auto-generated.
INSERT INTO WAREHOUSES (address) VALUES ('101 Distribution Way, Industrial Park East');
INSERT INTO WAREHOUSES (address) VALUES ('202 Logistics Ave, Central City');
INSERT INTO WAREHOUSES (address) VALUES ('303 Fulfillment Rd, Metro West');
INSERT INTO WAREHOUSES (address) VALUES ('404 Supply Chain Blvd, North Point');
INSERT INTO WAREHOUSES (address) VALUES ('505 Inventory Lane, South Side Docks');
INSERT INTO WAREHOUSES (address) VALUES ('606 Storage St, Airport Business Complex');
INSERT INTO WAREHOUSES (address) VALUES ('707 Goods In Rd, Trade Zone Alpha');
INSERT INTO WAREHOUSES (address) VALUES ('808 Dispatch Dr, Sector Beta');
INSERT INTO WAREHOUSES (address) VALUES ('909 Cargo Ct, Freight Terminal Gamma');
INSERT INTO WAREHOUSES (address) VALUES ('110 Pallet Place, Warehouse District');
INSERT INTO WAREHOUSES (address) VALUES ('121 Receiving Run, Port Authority Area');
INSERT INTO WAREHOUSES (address) VALUES ('132 Stockpile Square, Industrial Park West');
INSERT INTO WAREHOUSES (address) VALUES ('143 Haulage Heights, Central Logistics Hub');
INSERT INTO WAREHOUSES (address) VALUES ('154 Transit Terrace, Metro East');
INSERT INTO WAREHOUSES (address) VALUES ('165 Bulk Bay, North Industrial Zone');
INSERT INTO WAREHOUSES (address) VALUES ('176 Carrier Crescent, South Docks Extension');
INSERT INTO WAREHOUSES (address) VALUES ('187 Depot Drive, Airport Cargo Village');
INSERT INTO WAREHOUSES (address) VALUES ('198 Forwarding Fairway, Trade Zone Delta');
INSERT INTO WAREHOUSES (address) VALUES ('209 Movement Mews, Sector Epsilon');
INSERT INTO WAREHOUSES (address) VALUES ('220 Container Close, Freight Terminal Zeta');

-- Sample Data for TUSERS Table (20 Rows)
-- Note: ID is auto-generated. Assuming shop_id and warehouse_id range from 1 to 20.
-- DTYPE indicates user type (e.g., Customer, Manager, Admin).
INSERT INTO TUSERS ("birthDate", "isAdmin", shop_id, warehouse_id, "DTYPE", "billingAddress", "cardNumber", login, "name", "password", "shippingAddress", surname)
VALUES (TO_DATE('1990-05-15', 'YYYY-MM-DD'), 'N', NULL, NULL, 'Customer', '1 Apple St', '1111-2222-3333-4444', 'johndoe', 'John', 'pass1', '1 Apple St', 'Doe');
INSERT INTO TUSERS ("birthDate", "isAdmin", shop_id, warehouse_id, "DTYPE", "billingAddress", "cardNumber", login, "name", "password", "shippingAddress", surname)
VALUES (TO_DATE('1985-11-20', 'YYYY-MM-DD'), 'N', NULL, NULL, 'Customer', '2 Banana Ave', '2222-3333-4444-5555', 'janesmith', 'Jane', 'pass2', '5 Cherry Ln', 'Smith');
INSERT INTO TUSERS ("birthDate", "isAdmin", shop_id, warehouse_id, "DTYPE", "billingAddress", "cardNumber", login, "name", "password", "shippingAddress", surname)
VALUES (TO_DATE('1988-02-10', 'YYYY-MM-DD'), 'Y', 1, 1, 'Admin', '3 Coconut Cres', '3333-4444-5555-6666', 'adminuser', 'Admin', 'adminpass', '3 Coconut Cres', 'User');
INSERT INTO TUSERS ("birthDate", "isAdmin", shop_id, warehouse_id, "DTYPE", "billingAddress", "cardNumber", login, "name", "password", "shippingAddress", surname)
VALUES (TO_DATE('1995-07-01', 'YYYY-MM-DD'), 'N', 2, NULL, 'Manager', '4 Date Dr', '4444-5555-6666-7777', 'shopmgr1', 'Shop', 'mgrpass1', '4 Date Dr', 'ManagerOne');
INSERT INTO TUSERS ("birthDate", "isAdmin", shop_id, warehouse_id, "DTYPE", "billingAddress", "cardNumber", login, "name", "password", "shippingAddress", surname)
VALUES (TO_DATE('1992-09-25', 'YYYY-MM-DD'), 'N', NULL, 2, 'Manager', '5 Elderberry Est', '5555-6666-7777-8888', 'whsemgr1', 'Warehouse', 'mgrpass2', '5 Elderberry Est', 'ManagerTwo');
INSERT INTO TUSERS ("birthDate", "isAdmin", shop_id, warehouse_id, "DTYPE", "billingAddress", "cardNumber", login, "name", "password", "shippingAddress", surname)
VALUES (TO_DATE('2000-01-30', 'YYYY-MM-DD'), 'N', NULL, NULL, 'Customer', '6 Fig Freeway', '6666-7777-8888-9999', 'peterp', 'Peter', 'pass3', '6 Fig Freeway', 'Parker');
INSERT INTO TUSERS ("birthDate", "isAdmin", shop_id, warehouse_id, "DTYPE", "billingAddress", "cardNumber", login, "name", "password", "shippingAddress", surname)
VALUES (TO_DATE('1983-03-12', 'YYYY-MM-DD'), 'N', NULL, NULL, 'Customer', '7 Grape Grove', '7777-8888-9999-0000', 'lois_l', 'Lois', 'pass4', '7 Grape Grove', 'Lane');
INSERT INTO TUSERS ("birthDate", "isAdmin", shop_id, warehouse_id, "DTYPE", "billingAddress", "cardNumber", login, "name", "password", "shippingAddress", surname)
VALUES (TO_DATE('1979-12-08', 'YYYY-MM-DD'), 'N', 3, NULL, 'Manager', '8 Honeydew Hts', '8888-9999-0000-1111', 'shopmgr2', 'Grocery', 'mgrpass3', '8 Honeydew Hts', 'ManagerThree');
INSERT INTO TUSERS ("birthDate", "isAdmin", shop_id, warehouse_id, "DTYPE", "billingAddress", "cardNumber", login, "name", "password", "shippingAddress", surname)
VALUES (TO_DATE('1998-06-18', 'YYYY-MM-DD'), 'N', NULL, NULL, 'Customer', '9 Iceberg Isle', '9999-0000-1111-2222', 'brucew', 'Bruce', 'pass5', 'Wayne Manor', 'Wayne');
INSERT INTO TUSERS ("birthDate", "isAdmin", shop_id, warehouse_id, "DTYPE", "billingAddress", "cardNumber", login, "name", "password", "shippingAddress", surname)
VALUES (TO_DATE('1991-04-22', 'YYYY-MM-DD'), 'N', NULL, NULL, 'Customer', '10 Jackfruit Jct', '0000-1111-2222-3333', 'clark_k', 'Clark', 'pass6', 'Daily Planet', 'Kent');
INSERT INTO TUSERS ("birthDate", "isAdmin", shop_id, warehouse_id, "DTYPE", "billingAddress", "cardNumber", login, "name", "password", "shippingAddress", surname)
VALUES (TO_DATE('1986-10-14', 'YYYY-MM-DD'), 'Y', NULL, NULL, 'Admin', '11 Kiwi Knoll', '1111-0000-9999-8888', 'superadmin', 'Super', 'superpass', '11 Kiwi Knoll', 'Admin');
INSERT INTO TUSERS ("birthDate", "isAdmin", shop_id, warehouse_id, "DTYPE", "billingAddress", "cardNumber", login, "name", "password", "shippingAddress", surname)
VALUES (TO_DATE('1993-08-05', 'YYYY-MM-DD'), 'N', NULL, 5, 'Manager', '12 Lemon Loop', '2222-1111-0000-7777', 'whsemgr2', 'Inventory', 'mgrpass4', '12 Lemon Loop', 'Control');
INSERT INTO TUSERS ("birthDate", "isAdmin", shop_id, warehouse_id, "DTYPE", "billingAddress", "cardNumber", login, "name", "password", "shippingAddress", surname)
VALUES (TO_DATE('1999-02-28', 'YYYY-MM-DD'), 'N', NULL, NULL, 'Customer', '13 Mango Manor', '3333-2222-1111-6666', 'diana_p', 'Diana', 'pass7', 'Themyscira', 'Prince');
INSERT INTO TUSERS ("birthDate", "isAdmin", shop_id, warehouse_id, "DTYPE", "billingAddress", "cardNumber", login, "name", "password", "shippingAddress", surname)
VALUES (TO_DATE('1981-07-11', 'YYYY-MM-DD'), 'N', 6, NULL, 'Manager', '14 Nectarine Nook', '4444-3333-2222-5555', 'shopmgr3', 'Sporty', 'mgrpass5', '14 Nectarine Nook', 'Spice');
INSERT INTO TUSERS ("birthDate", "isAdmin", shop_id, warehouse_id, "DTYPE", "billingAddress", "cardNumber", login, "name", "password", "shippingAddress", surname)
VALUES (TO_DATE('1996-11-01', 'YYYY-MM-DD'), 'N', NULL, NULL, 'Customer', '15 Olive Oasis', '5555-4444-3333-4444', 'barry_a', 'Barry', 'pass8', 'Central City', 'Allen');
INSERT INTO TUSERS ("birthDate", "isAdmin", shop_id, warehouse_id, "DTYPE", "billingAddress", "cardNumber", login, "name", "password", "shippingAddress", surname)
VALUES (TO_DATE('1989-01-19', 'YYYY-MM-DD'), 'N', NULL, NULL, 'Customer', '16 Papaya Place', '6666-5555-4444-3333', 'hal_j', 'Hal', 'pass9', 'Coast City', 'Jordan');
INSERT INTO TUSERS ("birthDate", "isAdmin", shop_id, warehouse_id, "DTYPE", "billingAddress", "cardNumber", login, "name", "password", "shippingAddress", surname)
VALUES (TO_DATE('1975-05-29', 'YYYY-MM-DD'), 'Y', 9, 9, 'Admin', '17 Quince Quay', '7777-6666-5555-2222', 'masteradmin', 'Master', 'masterpass', '17 Quince Quay', 'Control');
INSERT INTO TUSERS ("birthDate", "isAdmin", shop_id, warehouse_id, "DTYPE", "billingAddress", "cardNumber", login, "name", "password", "shippingAddress", surname)
VALUES (TO_DATE('1994-09-09', 'YYYY-MM-DD'), 'N', NULL, 10, 'Manager', '18 Raspberry Row', '8888-7777-6666-1111', 'whsemgr3', 'Logistics', 'mgrpass6', '18 Raspberry Row', 'Lead');
INSERT INTO TUSERS ("birthDate", "isAdmin", shop_id, warehouse_id, "DTYPE", "billingAddress", "cardNumber", login, "name", "password", "shippingAddress", surname)
VALUES (TO_DATE('2001-03-03', 'YYYY-MM-DD'), 'N', NULL, NULL, 'Customer', '19 Strawberry St', '9999-8888-7777-0000', 'arthur_c', 'Arthur', 'pass10', 'Atlantis', 'Curry');
INSERT INTO TUSERS ("birthDate", "isAdmin", shop_id, warehouse_id, "DTYPE", "billingAddress", "cardNumber", login, "name", "password", "shippingAddress", surname)
VALUES (TO_DATE('1987-06-24', 'YYYY-MM-DD'), 'N', 15, NULL, 'Manager', '20 Tomato Terrace', '0000-9999-8888-1111', 'shopmgr4', 'Office', 'mgrpass7', '20 Tomato Terrace', 'SuppliesMgr');

-- Sample Data for CARTS Table (20 Rows)
-- Note: ID is auto-generated. Assuming customer_id and manager_id are valid TUSERS IDs (1-20).
-- Assigning customers (users 1, 2, 6, 7, 9, 10, 13, 15, 16, 19) and managers (users 4, 5, 8, 12, 14, 18, 20)
INSERT INTO CARTS (group_id, product_id, customer_id, manager_id) VALUES (1, 1, 1, NULL);
INSERT INTO CARTS (group_id, product_id, customer_id, manager_id) VALUES (1, 2, 2, 4);
INSERT INTO CARTS (group_id, product_id, customer_id, manager_id) VALUES (1, 3, 6, NULL);
INSERT INTO CARTS (group_id, product_id, customer_id, manager_id) VALUES (1, 4, 7, 8);
INSERT INTO CARTS (group_id, product_id, customer_id, manager_id) VALUES (1, 5, 9, NULL);
INSERT INTO CARTS (group_id, product_id, customer_id, manager_id) VALUES (1, 6, 10, NULL);
INSERT INTO CARTS (group_id, product_id, customer_id, manager_id) VALUES (1, 7, 13, 14);
INSERT INTO CARTS (group_id, product_id, customer_id, manager_id) VALUES (1, 8, 15, NULL);
INSERT INTO CARTS (group_id, product_id, customer_id, manager_id) VALUES (1, 9, 16, NULL);
INSERT INTO CARTS (group_id, product_id, customer_id, manager_id) VALUES (1, 10, 19, NULL);
INSERT INTO CARTS (group_id, product_id, customer_id, manager_id) VALUES (1, 11, 1, 5);
INSERT INTO CARTS (group_id, product_id, customer_id, manager_id) VALUES (1, 12, 2, NULL);
INSERT INTO CARTS (group_id, product_id, customer_id, manager_id) VALUES (1, 13, 6, 12);
INSERT INTO CARTS (group_id, product_id, customer_id, manager_id) VALUES (1, 14, 7, NULL);
INSERT INTO CARTS (group_id, product_id, customer_id, manager_id) VALUES (1, 15, 9, 18);
INSERT INTO CARTS (group_id, product_id, customer_id, manager_id) VALUES (1, 16, 10, 20);
INSERT INTO CARTS (group_id, product_id, customer_id, manager_id) VALUES (1, 17, 13, NULL);
INSERT INTO CARTS (group_id, product_id, customer_id, manager_id) VALUES (1, 18, 15, 4);
INSERT INTO CARTS (group_id, product_id, customer_id, manager_id) VALUES (1, 19, NULL, 8);
INSERT INTO CARTS (group_id, product_id, customer_id, manager_id) VALUES (1, 20, NULL, 5);

-- Sample Data for PRODUCTS Table (20 Rows)
-- Note: ID is auto-generated. Assuming cart_id (1-20), shop_id (1-20), warehouse_id (1-20) are valid IDs.
INSERT INTO PRODUCTS (price, quantity, shop_id, warehouse_id, description, title) VALUES (599.99, 1, 1, 1, 'Latest generation smartphone', 'Smartphone X');
INSERT INTO PRODUCTS (price, quantity, shop_id, warehouse_id, description, title) VALUES (49.99, 2, 1, 1, 'Wireless Bluetooth earbuds', 'Earbuds Pro');
INSERT INTO PRODUCTS (price, quantity, shop_id, warehouse_id, description, title) VALUES (75.50, 1, 2, 3, 'Stylish summer dress', 'Floral Sundress');
INSERT INTO PRODUCTS (price, quantity, shop_id, warehouse_id, description, title) VALUES (4.25, 5, 3, 4, 'Organic whole milk, 1 gallon', 'Organic Milk');
INSERT INTO PRODUCTS (price, quantity, shop_id, warehouse_id, description, title) VALUES (19.95, 1, 4, 6, 'Bestselling mystery novel', 'The Silent Witness');
INSERT INTO PRODUCTS (price, quantity, shop_id, warehouse_id, description, title) VALUES (299.00, 10, 5, 5, 'Comfortable three-seater sofa', 'Living Room Sofa');
INSERT INTO PRODUCTS (price, quantity, shop_id, warehouse_id, description, title) VALUES (89.99, 1, 6, 7, 'Two-person camping tent', 'Weekend Tent');
INSERT INTO PRODUCTS (price, quantity, shop_id, warehouse_id, description, title) VALUES (25.00, 3, 7, 8, 'Educational building block set', 'Creative Blocks');
INSERT INTO PRODUCTS (price, quantity, shop_id, warehouse_id, description, title) VALUES (15.75, 2, 8, 9, 'Anti-aging facial cream', 'Revitalizing Cream');
INSERT INTO PRODUCTS (price, quantity, shop_id, warehouse_id, description, title) VALUES (129.99, 15, 9, 10, 'Cordless power drill kit', 'Power Drill Set');
INSERT INTO PRODUCTS (price, quantity, shop_id, warehouse_id, description, title) VALUES (22.50, 1, 10, 11, 'Large bag of dry dog food', 'Premium Dog Kibble');
INSERT INTO PRODUCTS (price, quantity, shop_id, warehouse_id, description, title) VALUES (450.00, 1, 11, 12, 'Acoustic guitar with carrying case', 'Acoustic Guitar Pack');
INSERT INTO PRODUCTS (price, quantity, shop_id, warehouse_id, description, title) VALUES (55.00, 1, 12, 13, 'Set of acrylic paints and brushes', 'Artist Paint Set');
INSERT INTO PRODUCTS (price, quantity, shop_id, warehouse_id, description, title) VALUES (65.80, 2, 13, 14, 'Synthetic blend motor oil, 5 quarts', 'Motor Oil 5W-30');
INSERT INTO PRODUCTS (price, quantity, shop_id, warehouse_id, description, title) VALUES (12.99, 4, 14, 15, 'Indoor flowering plant seeds', 'Rose Seeds Mix');
INSERT INTO PRODUCTS (price, quantity, shop_id, warehouse_id, description, title) VALUES (199.50, 20, 15, 16, 'Ergonomic office chair', 'Comfort Office Chair');
INSERT INTO PRODUCTS (price, quantity, shop_id, warehouse_id, description, title) VALUES (18.00, 1, 16, 17, 'Single-origin coffee beans, 1 lb', 'Ethiopian Yirgacheffe Beans');
INSERT INTO PRODUCTS (price, quantity, shop_id, warehouse_id, description, title) VALUES (3.50, 6, 17, 18, 'Freshly baked croissants', 'Butter Croissant');
INSERT INTO PRODUCTS (price, quantity, shop_id, warehouse_id, description, title) VALUES (5.99, 2, 18, 19, 'Organic Gala apples, 2 lbs', 'Organic Apples');
INSERT INTO PRODUCTS (price, quantity, shop_id, warehouse_id, description, title) VALUES (89.95, 1, 19, 20, 'High-performance blender', 'Power Blender 1200');

-- Sample Data for COMMENTS Table (20 Rows)
-- Note: ID is auto-generated. Assuming commentOwner_id (1-20), parentComment_id (NULL or 1-20), whichProductCommented_id (1-20) are valid IDs.
INSERT INTO COMMENTS ("commentOwner_id", "parentComment_id", rating, "whichProductCommented_id", "commentBody", "commentTitle")
VALUES (1, NULL, 4.5, 1, 'Great phone, very fast and responsive.', 'Excellent Smartphone!');
INSERT INTO COMMENTS ("commentOwner_id", "parentComment_id", rating, "whichProductCommented_id", "commentBody", "commentTitle")
VALUES (2, NULL, 5.0, 3, 'Love this dress, fits perfectly!', 'Beautiful Dress');
INSERT INTO COMMENTS ("commentOwner_id", "parentComment_id", rating, "whichProductCommented_id", "commentBody", "commentTitle")
VALUES (6, 1, 4.0, 1, 'Agreed, battery life could be a bit better though.', 'Re: Excellent Smartphone!');
INSERT INTO COMMENTS ("commentOwner_id", "parentComment_id", rating, "whichProductCommented_id", "commentBody", "commentTitle")
VALUES (7, NULL, 3.0, 4, 'Good milk, but a bit pricey compared to others.', 'Decent Organic Milk');
INSERT INTO COMMENTS ("commentOwner_id", "parentComment_id", rating, "whichProductCommented_id", "commentBody", "commentTitle")
VALUES (9, NULL, 5.0, 5, 'Put this book down! Highly recommend.', 'Amazing Read!');
INSERT INTO COMMENTS ("commentOwner_id", "parentComment_id", rating, "whichProductCommented_id", "commentBody", "commentTitle")
VALUES (10, NULL, 4.0, 7, 'Tent was easy to set up and kept us dry.', 'Good Value Tent');
INSERT INTO COMMENTS ("commentOwner_id", "parentComment_id", rating, "whichProductCommented_id", "commentBody", "commentTitle")
VALUES (13, NULL, 4.8, 9, 'My skin feels great after using this cream.', 'Effective Cream');
INSERT INTO COMMENTS ("commentOwner_id", "parentComment_id", rating, "whichProductCommented_id", "commentBody", "commentTitle")
VALUES (15, NULL, 5.0, 12, 'Sounds beautiful, great value for beginners.', 'Fantastic Guitar');
INSERT INTO COMMENTS ("commentOwner_id", "parentComment_id", rating, "whichProductCommented_id", "commentBody", "commentTitle")
VALUES (16, 5, 5.0, 5, 'Yes! The ending was a complete surprise.', 'Re: Amazing Read!');
INSERT INTO COMMENTS ("commentOwner_id", "parentComment_id", rating, "whichProductCommented_id", "commentBody", "commentTitle")
VALUES (19, NULL, 3.5, 13, 'Good quality paints, nice selection of colors.', 'Nice Paint Set');
INSERT INTO COMMENTS ("commentOwner_id", "parentComment_id", rating, "whichProductCommented_id", "commentBody", "commentTitle")
VALUES (1, NULL, 4.2, 17, 'Rich flavor, makes a great morning coffee.', 'Tasty Coffee Beans');
INSERT INTO COMMENTS ("commentOwner_id", "parentComment_id", rating, "whichProductCommented_id", "commentBody", "commentTitle")
VALUES (2, NULL, 5.0, 18, 'Best croissants I have had outside of Paris!', 'Authentic Croissants');
INSERT INTO COMMENTS ("commentOwner_id", "parentComment_id", rating, "whichProductCommented_id", "commentBody", "commentTitle")
VALUES (6, 12, 5.0, 18, 'Totally agree! So flaky and buttery.', 'Re: Authentic Croissants');
INSERT INTO COMMENTS ("commentOwner_id", "parentComment_id", rating, "whichProductCommented_id", "commentBody", "commentTitle")
VALUES (7, NULL, 4.0, 19, 'Fresh and crisp apples.', 'Good Apples');
INSERT INTO COMMENTS ("commentOwner_id", "parentComment_id", rating, "whichProductCommented_id", "commentBody", "commentTitle")
VALUES (9, NULL, 4.7, 20, 'Blends smoothies perfectly, very powerful.', 'Great Blender');
INSERT INTO COMMENTS ("commentOwner_id", "parentComment_id", rating, "whichProductCommented_id", "commentBody", "commentTitle")
VALUES (10, 15, 4.5, 20, 'It is a bit loud, but worth it for the performance.', 'Re: Great Blender');
INSERT INTO COMMENTS ("commentOwner_id", "parentComment_id", rating, "whichProductCommented_id", "commentBody", "commentTitle")
VALUES (13, NULL, 2.5, 2, 'Sound quality is just okay, expected better for the price.', 'Disappointing Earbuds');
INSERT INTO COMMENTS ("commentOwner_id", "parentComment_id", rating, "whichProductCommented_id", "commentBody", "commentTitle")
VALUES (15, NULL, 5.0, 8, 'My kids love these blocks, hours of fun.', 'Excellent Toy');
INSERT INTO COMMENTS ("commentOwner_id", "parentComment_id", rating, "whichProductCommented_id", "commentBody", "commentTitle")
VALUES (16, NULL, 4.0, 11, 'Good food, my dog enjoys it.', 'Dog Likes It');
INSERT INTO COMMENTS ("commentOwner_id", "parentComment_id", rating, "whichProductCommented_id", "commentBody", "commentTitle")
VALUES (19, NULL, 3.8, 14, 'Standard motor oil, does the job.', 'Works Fine');
